We are still building up to a solution for the [three girls
problem](../02/three_girls).

We have more of the building blocks we need.

First we load the Numpy library.

In [1]:
# Load the Numpy package, and rename to "np"
import numpy as np

We are going to simulate 10000 families, each with four children.

Here we put together some things you've seen before.  We are creating a Numpy array from an empty list.  We get an empty array.

In [2]:
# Make an empty array to store counts of girls in each family
counts = np.array([])
counts

array([], dtype=float64)

`counts` will eventually have 10000 elements where each will be the number of girls in one simulated family.

Remembering [function arguments](function_arguments), here is how we make
an array that simulates a family of four children:

In [3]:
family = np.random.randint(2, size=4)
family

array([1, 0, 0, 1])

We represented girls with a value of one. We can count the number of girls by using the `np.sum` function on the `family` array:

In [4]:
count = np.sum(family)
count

2

We want to build up a lot of counts, in the `counts` array, so we start by appending the `count` value:

In [5]:
# Store the count in the counts array.
counts = np.append(counts, count)
counts

array([2.])

We can do this again in a single cell, like this:

In [6]:
# A second family
family = np.random.randint(2, size=4)
count = np.sum(family)
# Store the count in the counts array.
counts = np.append(counts, count)
counts

array([2., 2.])

To add another family, we just repeat the same:

In [7]:
# A third family
family = np.random.randint(2, size=4)
count = np.sum(family)
# Store the count in the counts array.
counts = np.append(counts, count)
counts

array([2., 2., 2.])

Obviously this is getting a bit boring and repetitive. Surely we can do better.

Yes indeed, we can use a *for loop*.  Here's a preview:

In [8]:
# Reset the counts array to empty.
counts = np.array([])
# Repeat the indented stuff 10000 times.
for i in np.arange(10000):
    # The procedure for one family.
    family = np.random.randint(2, size=4)
    count = np.sum(family)
    # Store the count in the counts array.
    counts = np.append(counts, count)
counts

array([2., 2., 1., ..., 2., 0., 1.])

Now we have a count of the number of girls, from 10000 simulated families:

In [9]:
len(counts)

10000

How did that work?  On to [iteration with for loops](Iteration).